version: '3'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php
    links: 
      - php
    restart: unless-stopped

  php:
    image: php:7-fpm-alpine
    volumes:
      - ./src:/var/www/html
    networks:
      - nginx-php
    restart: unless-stopped

networks:
  nginx-php:
